apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- deployment.yml
resources:
- ../base
images:
- name: humancat-frontend-image
  newName: 374509772175.dkr.ecr.ap-northeast-2.amazonaws.com/humancat-frontend
  newTag: "20231115.131737"
namespace: gitops
