apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- deployment.yml
resources:
- ../base
images:
- name: humancat-backend-image
  newName: 374509772175.dkr.ecr.ap-northeast-2.amazonaws.com/humancat-backend
  newTag: 0.0.1-backend.02
namespace: gitops
